In [14]:
import pyarrow.parquet as pq
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sweetviz as sv

In [2]:
train = pd.read_csv('train.csv')
print(train.shape)
train.head()

(106800, 15)


eeg_id  eeg_sub_id  eeg_label_offset_seconds  spectrogram_id  \
0  1628180742           0                       0.0          353733   
1  1628180742           1                       6.0          353733   
2  1628180742           2                       8.0          353733   
3  1628180742           3                      18.0          353733   
4  1628180742           4                      24.0          353733   

   spectrogram_sub_id  spectrogram_label_offset_seconds    label_id  \
0                   0                               0.0   127492639   
1                   1                               6.0  3887563113   
2                   2                               8.0  1142670488   
3                   3                              18.0  2718991173   
4                   4                              24.0  3080632009   

   patient_id expert_consensus  seizure_vote  lpd_vote  gpd_vote  lrda_vote  \
0       42516          Seizure             3         0         0          0   
1       42516          Seizure             3         0         0          0   
2       42516          Seizure             3         0         0          0   
3       42516          Seizure             3         0         0          0   
4       42516          Seizure             3         0         0          0   

   grda_vote  other_vote  
0          0           0  
1          0           0  
2          0           0  
3          0           0  
4          0           0

In [6]:
#example eeg = 1628180742
sample_table = pq.read_table('C:/Users/kakka/PycharmProjects/ProjectM/HMS-DL/train_eegs/1628180742.parquet')
sample_table

pyarrow.Table
Fp1: float
F3: float
C3: float
P3: float
F7: float
T3: float
T5: float
O1: float
Fz: float
Cz: float
Pz: float
Fp2: float
F4: float
C4: float
P4: float
F8: float
T4: float
T6: float
O2: float
EKG: float
----
Fp1: [[-80.52,-80.45,-80.21,-84.71,-90.57,...,-144.66,-140.88,-133.73,-141.45,-138.67]]
F3: [[-70.54,-70.33,-75.87,-75.34,-80.79,...,-147.81,-153,-141.77,-151.14,-147.21]]
C3: [[-80.11,-81.76,-82.05,-87.48,-93,...,-129.82,-129.53,-121.9,-127.19,-122.82]]
P3: [[-108.75,-107.67,-106.01,-108.97,-113.87,...,-129.46,-129.02,-122.37,-128.7,-128.29]]
F7: [[-120.33,-120.77,-117.5,-121.41,-129.96,...,-157.51,-154.06,-158.75,-163.46,-164.87]]
T3: [[-88.62,-90.82,-87.49,-94.75,-102.86,...,-124,-131.22,-123.55,-124.31,-124.24]]
T5: [[-101.75,-104.26,-99.59,-105.37,-118.6,...,-124.57,-128.38,-127.73,-129.48,-129.34]]
O1: [[-104.49,-99.73,-96.82,-100.28,-101.1,...,-94.82,-95,-93.09,-94.42,-95.32]]
Fz: [[-99.13,-99.07,-119.68,-113.84,-107.66,...,-153.07,-140.82,-125.23,-140.87,-136.

In [7]:
sample_df = sample_table.to_pandas()
sample_df

Fp1          F3          C3          P3          F7          T3  \
0      -80.519997  -70.540001  -80.110001 -108.750000 -120.330002  -88.620003   
1      -80.449997  -70.330002  -81.760002 -107.669998 -120.769997  -90.820000   
2      -80.209999  -75.870003  -82.050003 -106.010002 -117.500000  -87.489998   
3      -84.709999  -75.339996  -87.480003 -108.970001 -121.410004  -94.750000   
4      -90.570000  -80.790001  -93.000000 -113.870003 -129.960007 -102.860001   
...           ...         ...         ...         ...         ...         ...   
17995 -144.660004 -147.809998 -129.820007 -129.460007 -157.509995 -124.000000   
17996 -140.880005 -153.000000 -129.529999 -129.020004 -154.059998 -131.220001   
17997 -133.729996 -141.770004 -121.900002 -122.370003 -158.750000 -123.550003   
17998 -141.449997 -151.139999 -127.190002 -128.699997 -163.460007 -124.309998   
17999 -138.669998 -147.210007 -122.820000 -128.289993 -164.869995 -124.239998   

               T5          O1          Fz          Cz         Pz         Fp2  \
0     -101.750000 -104.489998  -99.129997  -90.389999 -97.040001  -77.989998   
1     -104.260002  -99.730003  -99.070000  -92.290001 -96.019997  -84.500000   
2      -99.589996  -96.820000 -119.680000  -99.360001 -91.110001  -99.440002   
3     -105.370003 -100.279999 -113.839996 -102.059998 -95.040001  -99.230003   
4     -118.599998 -101.099998 -107.660004 -102.339996 -98.510002  -95.300003   
...           ...         ...         ...         ...        ...         ...   
17995 -124.570000  -94.820000 -153.070007 -121.110001 -86.459999 -132.520004   
17996 -128.380005  -95.000000 -140.820007 -114.639999 -84.379997 -115.339996   
17997 -127.730003  -93.089996 -125.230003 -106.489998 -83.419998 -112.720001   
17998 -129.479996  -94.419998 -140.869995 -113.339996 -83.519997 -129.300003   
17999 -129.339996  -95.320000 -136.789993 -112.820000 -84.660004 -129.380005   

               F4          C4          P4          F8         T4          T6  \
0      -88.830002 -112.120003 -108.110001  -95.949997 -98.360001 -121.730003   
1      -84.989998 -115.610001 -103.860001  -97.470001 -89.290001 -115.500000   
2     -104.589996 -127.529999 -113.349998  -95.870003 -96.019997 -123.879997   
3     -101.220001 -125.769997 -111.889999  -97.459999 -97.180000 -128.940002   
4      -88.930000 -115.639999  -99.800003  -97.500000 -88.730003 -114.849998   
...           ...         ...         ...         ...        ...         ...   
17995 -138.339996 -128.970001  -71.300003 -114.480003 -86.709999 -114.959999   
17996 -119.230003 -114.709999  -70.989998  -92.129997 -79.639999 -116.139999   
17997 -103.209999 -107.629997  -61.869999  -97.910004 -77.150002 -106.500000   
17998 -118.650002 -117.589996  -71.879997  -99.279999 -83.900002 -116.160004   
17999 -123.180000 -122.889999  -79.910004 -101.459999 -84.339996 -125.989998   

               O2        EKG  
0     -106.449997   7.920000  
1     -102.059998  29.219999  
2     -105.790001  45.740002  
3     -109.889999  83.870003  
4     -100.250000  97.769997  
...           ...        ...  
17995  -81.500000 -20.070000  
17996  -81.879997  10.600000  
17997  -75.339996  -2.060000  
17998  -81.410004   2.820000  
17999  -89.110001  35.279999  

[18000 rows x 20 columns]

In [16]:
report = sv.analyze(sample_df)
report.show_html('Advertising.html')

                                             |          | [  0%]   00:00 -> (? left)

Report Advertising.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.


In [18]:
sample_spec = pq.read_table('C:/Users/kakka/PycharmProjects/ProjectM/HMS-DL/train_spectrograms/353733.parquet')
sample_spec

pyarrow.Table
time: int64
LL_0.59: float
LL_0.78: float
LL_0.98: float
LL_1.17: float
LL_1.37: float
LL_1.56: float
LL_1.76: float
LL_1.95: float
LL_2.15: float
LL_2.34: float
LL_2.54: float
LL_2.73: float
LL_2.93: float
LL_3.13: float
LL_3.32: float
LL_3.52: float
LL_3.71: float
LL_3.91: float
LL_4.1: float
LL_4.3: float
LL_4.49: float
LL_4.69: float
LL_4.88: float
LL_5.08: float
LL_5.27: float
LL_5.47: float
LL_5.66: float
LL_5.86: float
LL_6.05: float
LL_6.25: float
LL_6.45: float
LL_6.64: float
LL_6.84: float
LL_7.03: float
LL_7.23: float
LL_7.42: float
LL_7.62: float
LL_7.81: float
LL_8.01: float
LL_8.2: float
LL_8.4: float
LL_8.59: float
LL_8.79: float
LL_8.98: float
LL_9.18: float
LL_9.38: float
LL_9.57: float
LL_9.77: float
LL_9.96: float
LL_10.16: float
LL_10.35: float
LL_10.55: float
LL_10.74: float
LL_10.94: float
LL_11.13: float
LL_11.33: float
LL_11.52: float
LL_11.72: float
LL_11.91: float
LL_12.11: float
LL_12.3: float
LL_12.5: float
LL_12.7: float
LL_12.89: float
LL_13.

In [19]:
sample_spec_df = sample_spec.to_pandas()
sample_spec_df

time  LL_0.59  LL_0.78  LL_0.98  LL_1.17  LL_1.37    LL_1.56    LL_1.76  \
0       1     4.26    10.98     9.05    13.65    11.49   8.930000  18.840000   
1       3     2.65     3.97    12.18    13.26    14.21  13.230000   9.650000   
2       5     4.18     4.53     8.77    14.26    13.36  16.559999  19.219999   
3       7     2.41     3.21     4.92     8.07     5.97  12.420000  10.820000   
4       9     2.29     2.44     2.77     4.62     5.39   7.080000   9.840000   
..    ...      ...      ...      ...      ...      ...        ...        ...   
315   631     6.36     6.59     6.60     7.30     4.48   8.400000  13.420000   
316   633     4.90     8.80     8.22     5.83    10.21  10.580000  10.250000   
317   635     6.07     7.85    11.26     9.20     8.18   9.130000  10.450000   
318   637     3.41     3.75     4.80     6.45     6.70   7.960000   8.160000   
319   639     2.88     3.71     4.02     6.07     5.63   5.460000   6.270000   

     LL_1.95    LL_2.15  ...  RP_18.16  RP_18.36  RP_18.55  RP_18.75  \
0      19.26  19.240000  ...      0.31      0.17      0.28      0.19   
1       8.11  11.280000  ...      0.15      0.13      0.14      0.24   
2      17.51  22.650000  ...      0.29      0.21      0.16      0.25   
3      14.96  21.809999  ...      0.33      0.51      0.49      0.64   
4      12.27  14.410000  ...      0.44      0.38      0.48      0.63   
..       ...        ...  ...       ...       ...       ...       ...   
315    13.85  16.010000  ...      0.14      0.05      0.06      0.04   
316    13.68  19.549999  ...      0.16      0.08      0.06      0.06   
317    15.09  23.020000  ...      0.15      0.13      0.13      0.13   
318     6.97   9.700000  ...      0.13      0.11      0.13      0.07   
319     4.99   6.220000  ...      0.16      0.13      0.14      0.16   

     RP_18.95  RP_19.14  RP_19.34  RP_19.53  RP_19.73  RP_19.92  
0        0.24      0.27      0.29      0.16      0.22      0.19  
1        0.24      0.36      0.35      0.31      0.36      0.40  
2        0.28      0.28      0.34      0.48      0.44      0.48  
3        0.58      0.42      0.32      0.31      0.32      0.33  
4        0.45      0.45      0.49      0.33      0.31      0.34  
..        ...       ...       ...       ...       ...       ...  
315      0.04      0.04      0.05      0.05      0.08      0.11  
316      0.07      0.04      0.06      0.09      0.07      0.08  
317      0.10      0.08      0.07      0.09      0.17      0.12  
318      0.11      0.12      0.09      0.16      0.19      0.19  
319      0.12      0.12      0.11      0.09      0.07      0.05  

[320 rows x 401 columns]

In [22]:
def sunkavalli(id,sub_id,offest_sec):
    pq_table = pq.read_table('C:/Users/kakka/PycharmProjects/ProjectM/HMS-DL/train_eegs/'+str(id)+'.parquet')
    pq_df = pq_table.to_pandas()
    start_range = int((offest_sec)*200)
    end_range = int((offest_sec+50)*200)
    pq_df.iloc[start_range:end_range]
    return pq_df.to_numpy()

In [23]:
sample = sunkavalli(1628180742,0,0.0)

In [27]:
print(sample)

[[ -80.52  -70.54  -80.11 ... -121.73 -106.45    7.92]
 [ -80.45  -70.33  -81.76 ... -115.5  -102.06   29.22]
 [ -80.21  -75.87  -82.05 ... -123.88 -105.79   45.74]
 ...
 [-133.73 -141.77 -121.9  ... -106.5   -75.34   -2.06]
 [-141.45 -151.14 -127.19 ... -116.16  -81.41    2.82]
 [-138.67 -147.21 -122.82 ... -125.99  -89.11   35.28]]


In [37]:
def kakka(id,sub_id,offest_sec):
    pq_table = pq.read_table('C:/Users/kakka/PycharmProjects/ProjectM/HMS-DL/train_spectrograms/'+str(id)+'.parquet')
    pq_df = pq_table.to_pandas()
    options = np.arange(int(offest_sec)+1,int(offest_sec+10),2)
    print(options)
    pq_df = pq_df.loc[pq_df['time'].isin(options)]
    return pq_df.to_numpy()

In [38]:
sample_spec = kakka(353733,0,0.0)

[1 3 5 7 9]


In [39]:
sample_spec

array([[ 1.        ,  4.26000023, 10.97999954, ...,  0.16      ,
         0.22      ,  0.19      ],
       [ 3.        ,  2.6500001 ,  3.97000003, ...,  0.31      ,
         0.36000001,  0.40000001],
       [ 5.        ,  4.17999983,  4.53000021, ...,  0.47999999,
         0.44      ,  0.47999999],
       [ 7.        ,  2.41000009,  3.21000004, ...,  0.31      ,
         0.31999999,  0.33000001],
       [ 9.        ,  2.28999996,  2.44000006, ...,  0.33000001,
         0.31      ,  0.34      ]])